[package]
name = "myrient-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
futures-util = "0.3.31"
myrient-filter = "0.1.0"
reqwest = { version = "0.12.12", features = ["stream"] }
rfd = "0.15.2"
tokio = { version = "1.43.0", features = ["full"] }
